language: node_js
node_js:
  - 'node'

script:
  nyc yarn test

after_success:
  yarn coverage

services:
  - postgresql

env:
  PASSWORD="elijah1234567890"
  DB_USER='postgres'
  HOST='localhost'
  DB='test'
  DB_PASSWORD='woody4real'
  DB_PORT=5432

before_script:
  - psql -c 'create database test1;' -U postgres
