language: node_js
node_js:
  - 'node'

script:
  nyc yarn test

after_success:
  yarn coverage

services:
  - postgresql

env:
- NODE_ENV=test

before_script:
  - psql -c 'create database test1;' -U postgres
